dcConsData = [
	{name:"조용.png", keywords:["조용", "정숙"], tags:["찬호티콘"]},
	{name:"금지.png", keywords:["금지"], tags:["찬호티콘"]},
	{name:"힘차이.png", keywords:["힘차이"], tags:["찬호티콘"]},
	{name:"야발.gif", keywords:["야발"], tags:["찬호티콘"]},
	{name:"ㅋㅋ.gif", keywords:["ㅋㅋ", "ㅋㅋㅋ"], tags:["철붕콘"]},
	{name:"그만해.png", keywords:["그만해"], tags:["양학충"]},
	{name:"양학충.png", keywords:["양학충"], tags:["양학충"]},
	{name:"마침.png", keywords:["계급"], tags:["양학충"]},
	{name:"어휴.png", keywords:["어휴"], tags:["철붕콘"]},
	{name:"꿈나무.png", keywords:["꿈나무"], tags:["철붕콘"]},
	{name:"힘의차이.png", keywords:["힘의차이"], tags:["철붕콘"]},
	{name:"강등.png", keywords:["강등"], tags:["철붕콘"]},
	{name:"돼지.png", keywords:["돼지"], tags:["철붕콘"]},
	{name:"똥캐.png", keywords:["똥캐"], tags:["철붕콘"]},
	{name:"랜뽑.png", keywords:["랜뽑"], tags:["철붕콘"]},
	{name:"방종.png", keywords:["방종"], tags:["철붕콘"]},
	{name:"설마.png", keywords:["설마"], tags:["철붕콘"]},
	{name:"ㅆㄺ.png", keywords:["ㅆㄺ", "쓰레기"], tags:["철붕콘"]},
	{name:"ㅇㅈ.png", keywords:["ㄹㅇ", "ㅇㅈ"], tags:["철붕콘"]},
	{name:"헤이만두.png", keywords:["헤이"], tags:["철붕콘"]},
	{name:"머레이.png", keywords:["머레이"], tags:["철붕콘"]},
	{name:"모르면.png", keywords:["모르면"], tags:["철붕콘"]},
	{name:"힘내.png", keywords:["힘내", "파이팅"], tags:["철붕콘"]},
	{name:"우승.png", keywords:["우승"], tags:["철붕콘"]},
	{name:"나보막.png", keywords:["보막"], tags:["철허세"]},
	{name:"낫쿨.png", keywords:["낫쿨"], tags:["철허세"]},
	{name:"딜캐.png", keywords:["딜캐"], tags:["철허세"]},
	{name:"파해.png", keywords:["파해", "파훼"], tags:["철허세"]},
	{name:"필살기.png", keywords:["화랑", "솟랑", "좆랑"], tags:["철허세"]},
	{name:"관짝.gif", keywords:["관짝"], tags:["철붕콘"]},
	{name:"드라군.png", keywords:["ㅗ"], tags:["철페페"]},
	{name:"물음표.png", keywords:["?", "??"], tags:["철페페"]},
	{name:"씹쿨람.png", keywords:["파림콜", "파쿨람"], tags:["철페페"]},
	{name:"조도유.png", keywords:["샤오유", "조도유"], tags:["철페페"]},
	{name:"혐키.png", keywords:["럭키", "혐키"], tags:["철페페"]},
	{name:"딿.gif", keywords:["딿"], tags:["철붕콘"]},
	{name:"현실.gif", keywords:["현실"], tags:["철붕콘"]},
	{name:"눈물.png", keywords:["눈물"], tags:["철붕콘"]}
];